version: '3.3'

services:
  postgresql:
    image: postgres:latest
    command: 'postgres -c max_connections=200 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    hostname: postgresql
    environment:
      - POSTGRES_PASSWORD=app123
      - POSTGRES_USER=app
      - POSTGRES_DB=rinhadb
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    networks:
      - app-network

  api1:
    image: diegolirio/rinha-kotlin-spring-postgres
    hostname: api1
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/rinhadb
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
    networks:
      - app-network

  api2:
    image: diegolirio/rinha-kotlin-spring-postgres
    hostname: api2
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/rinhadb
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '256MB'

networks:
  app-network:
    driver: bridge